hw4: hw4_raster.o hw4_functions.o
	gcc hw4_raster.o hw4_functions.o -o hw4

hw4_raster.o: hw4_raster.c
	gcc -c hw4_raster.c

hw4_functions.o: hw4_functions.c
	gcc -c hw4_functions.c

clean:
	rm -f *.o hw4