lec11: lec11_functions.o lec11_main.o
	gcc lec11_functions.o lec11_main.o -o lec11

lec11_functions.o: lec11_functions.c
	gcc -c lec11_functions.c

lec11_main.o: lec11_main.c
	gcc -c lec11_main.c

clean:
	rm -f *.o lec11