pe5: lab5_list.o lab5_functions.o
	gcc lab5_list.o lab5_functions.o -o lab5

lab5_list.o: lab5_list.c
	gcc -c lab5_list.c

lab5_functions.o: lab5_functions.c
	gcc -c lab5_functions.c

clean:
	rm -rf *.o lab5